---
- hosts: banuprod
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true
    - name: Upgrade all apt packages
      apt: upgrade=yes force_apt_get=yes
      become: true
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker-compose
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: javaproject1
        image: "tbanuprakash/project1:latest"
        state: started
        published_ports:
          - 0.0.0.0:8006:8080
